<?php
	$this->headMeta()->appendName('charset', 'utf-8');
	$this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1');
	$this->headMeta()->appendName('viewport', 'width=device-width');
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle('Collection Tracker');

	echo $this->doctype();
?>
<!--[if lt IE 7 ]> <html dir="ltr" lang="en-US" class="ie6"> <![endif]-->
<!--[if IE 7 ]>    <html dir="ltr" lang="en-US" class="ie7"> <![endif]-->
<!--[if IE 8 ]>    <html dir="ltr" lang="en-US" class="ie8"> <![endif]-->
<!--[if IE 9 ]>    <html dir="ltr" lang="en-US" class="ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html dir="ltr" lang="en-US"> <!--<![endif]-->
<head>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css'); ?>
</head>
<body>
	<header>
		<h1><?php echo $this->escape($this->title); ?></h1>
	</header>
	<div role="main">
		<?php echo $this->layout()->content; ?>
	</div>
</body>
</html>

