<?php
	$this->title = "My Albums";
	$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller' => 'music', 'action' => 'add' )); ?>">Add more</a></p>

<?php if( count($this->albums) > 0) { ?>

<table>
	<tr>
		<th>
			<a href="<?php echo $this->url(array('controller' => 'music')); ?>?sort=title&amp;sortorder=<?php echo $this->titleorder ?>">
				Title
			</a>
		</th>
		<th>
			<a href="<?php echo $this->url(array('controller' => 'music')); ?>?sort=artist&amp;sortorder=<?php echo $this->artistorder ?>">
				Artist
			</a>
		</th>
		<th>&nbsp;</th>
	</tr>
	
	<?php foreach($this->albums as $album) : ?>
	
	<tr>
		<td>
			<?php echo $this->escape($album->title);?>
		</td>
		<td>
			<?php echo $this->escape($album->artist);?></td>
		<td>
			<a href="<?php echo $this->url(array('controller' => 'music', 'action' => 'edit', 'id'=>$album->id )); ?>">Edit</a>
		</td>
		<td>
			<a href="<?php echo $this->url(array('controller' => 'music', 'action' => 'delete', 'id'=>$album->id )); ?>">Delete</a>
		</td>
	</tr>
	
	<?php endforeach; ?>
</table>

<?php } else {
	echo "<p>No albums found.</p>";
} ?>
	